import type { Metadata } from "next";
import "./ui/globals.css";
import { lusitana } from "./ui/fonts";

import * as React from 'react';
import { NextAppProvider } from '@toolpad/core/nextjs';
import { DashboardLayout } from '@toolpad/core/DashboardLayout';
import { PageContainer } from '@toolpad/core/PageContainer';
import { NAVIGATION } from './navigation'
import Logo from './ui/components/logo'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout(props) {
  const { children } = props;

  return (
    <html lang="en">
      <body
        className={`${lusitana.className} antialiased`}
        suppressHydrationWarning
      >
        <NextAppProvider
          navigation={NAVIGATION}
          branding={{
            logo: <Logo className="size-10" />,
            title: 'Politics',
            homeUrl: '/',
          }}
        >
          <DashboardLayout>
            {/* <PageContainer> */}
            {children}
            {/* </PageContainer> */}
          </DashboardLayout>
        </NextAppProvider>
      </body>
    </html >
  );
}
