import type { Metadata } from "next";
import "./ui/globals.css";
import { lusitana } from "./ui/fonts";

import { extendTheme } from '@mui/material/styles';
import { Navigation, Router } from '@toolpad/core/AppProvider';
import DashboardIcon from '@mui/icons-material/Dashboard';
import BarChartIcon from '@mui/icons-material/BarChart';
import AttachMoneyIcon from '@mui/icons-material/AttachMoney';

import Logo from './ui/components/logo'

import DescriptionIcon from '@mui/icons-material/Description';
import LayersIcon from '@mui/icons-material/Layers';


import * as React from 'react';
import { NextAppProvider } from '@toolpad/core/nextjs';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
// import { SessionProvider, signIn, signOut } from 'next-auth/react';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NAVIGATION: Navigation = [
  // {
  //     kind: 'header',
  //     title: 'Main items',
  // },
  {
    segment: 'game',
    title: 'Nueva nacion',
    icon: <LayersIcon />,
  },
  {
    kind: 'divider',
  },
  {
    kind: 'header',
    title: 'my nations',
  },
  {
    segment: '[nationId]',
    icon: <DescriptionIcon />,
    children: [
      {
        segment: 'dashboard',
        title: 'Dashboard',
        icon: <DashboardIcon />,
      },
      {
        segment: 'reports',
        title: 'Reports',
        icon: <BarChartIcon />,
        children: [
          {
            segment: 'economics',
            title: 'Economics',
            icon: <AttachMoneyIcon />,
          },
        ],
      },
    ]
  }
];

const theme = extendTheme({
  colorSchemes: { light: true, dark: true },
  colorSchemeSelector: 'class',
  breakpoints: {
    values: {
      xs: 0,
      sm: 600,
      md: 600,
      lg: 1200,
      xl: 1536,
    },
  },
});

// function useDemoRouter(initialPath: string): Router {
//     const [pathname, setPathname] = React.useState(initialPath);

//     const router = React.useMemo(() => {
//         return {
//             pathname,
//             searchParams: new URLSearchParams(),
//             navigate: (path: string | URL) => setPathname(String(path)),
//         };
//     }, [pathname]);

//     return router;
// }

// const AUTHENTICATION = {
//   signIn,
//   signOut,
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await auth();
  // const router = useDemoRouter('/game');

  return (
    <html lang="en">
      <body
        className={`${lusitana.className} antialiased`}
        suppressHydrationWarning
      >
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <NextAppProvider
            theme={theme}
            navigation={NAVIGATION}
            branding={{
              logo: <Logo className="size-10" />,
              title: 'Politics',
              homeUrl: '/',
            }}
          >
            {children}
          </NextAppProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
